#!/bin/sh
# -------------------------------------------------------------------------------
# Post-remove script for oracle-watchdog
# -------------------------------------------------------------------------------
set -e

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi

if [ "$1" = "purge" ]; then
    rm -rf /etc/oracle-watchdog
fi
